version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
      ZAPRITE_APP_URL: 'http://localhost:3000'
      ZAPRITE_API_URL: 'http://host.docker.internal:3000'
    volumes:
      - wordpress_data:/var/www/html
      - ../plugin:/var/www/html/wp-content/plugins/zaprite-payment-gateway

  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
