name: Zip Woo Plugin and Upload to Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip the folder
      run: |
        cd html/wp-content/plugins
        zip -r zaprite-payment-gateway.zip zaprite-payment-gateway

    - name: Get the version
      id: get_version
      run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zaprite-payment-gateway.zip
        asset_name: zaprite-payment-gateway.zip
        asset_content_type: application/zip