name: Zip Woo Plugin and Upload to Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the folder
        run: |
          zip -r zaprite-payment-gateway.zip zaprite-payment-gateway

      - name: Get the version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" ./zaprite-payment-gateway.zip \
            --title "Release $VERSION" \
            --notes ""
